# Generated by Django 5.0.6 on 2024-07-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='USN',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
